export default from './Modal'
export Body from './Body'
export Header from './Header'
export Footer from './Footer'
export Content from './Content'
export Title from './Title'
export Close from './Close'
